Repository TrystAI/restorers, pull requests merged in 2023-04, with the labels that each got.

#66 Documentation: Added documentation for blocks defined for NAFNet implementation
  restorers/model/nafnet/nafblock.py
  restorers/model/nafnet/nafnet.py
Labels: documentation

#67 docs: Add docstrings for restorers.evaluation module
  .github/workflows/tests.yml
  docs/evaluation/base.md
  docs/evaluation/lol_eval.md
  mkdocs.yml
  pyproject.toml
  requirements.txt
  restorers/evaluation/base.py
  restorers/evaluation/lol_eval.py
Labels: documentation

#68 docs: Add documentation for the dataloader, model, losses and inference module
  .github/PULL_REQUEST_TEMPLATE.md
  docs/dataloader/base.md
  docs/dataloader/base_low_light.md
  docs/dataloader/lol_dataloader.md
  docs/dataloader/mit_adobe_5k_dataloader.md
  docs/index.md
  docs/inference/base.md
  docs/inference/low_light.md
  docs/javascripts/mathjax.js
  docs/losses/charbonnier_loss.md
  docs/losses/psnr_loss.md
  docs/losses/spatial_consistency_loss.md
  docs/losses/zero_reference.md
  docs/models/mirnetv2.md
  docs/models/nafnet.md
  docs/models/zero_dce_model.md
  mkdocs.yml
  pyproject.toml
  restorers/dataloader/base/base_dataloader.py
  restorers/dataloader/base/base_low_light_dataloader.py
  restorers/dataloader/lol_dataloader.py
  restorers/evaluation/base.py
  restorers/evaluation/lol_eval.py
  restorers/inference/base.py
  restorers/inference/low_light.py
  restorers/losses/charbonnier_loss.py
  restorers/losses/psnr_loss.py
  restorers/losses/spatial_consistency_loss.py
  restorers/losses/zero_reference.py
  restorers/model/mirnetv2/mirnet.py
  restorers/model/mirnetv2/rcb.py
  restorers/model/mirnetv2/recursive_residual_group.py
  restorers/model/mirnetv2/skff.py
  restorers/model/nafnet/__init__.py
  restorers/model/nafnet/blocks.py
  restorers/model/nafnet/nafblock.py
  restorers/model/nafnet/nafnet.py
  restorers/model/zero_dce/__init__.py
  restorers/model/zero_dce/dw_conv.py
  restorers/model/zero_dce/fast_zero_dce.py
  restorers/model/zero_dce/zero_dce.py
  restorers/tests/model/mirnetv2/test_mirnetv2.py
  restorers/tests/model/zero_dce/test_dce_net.py
Labels: documentation

#69 docs: Deploy
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  docs/examples/evaluate_low_light.ipynb
  docs/examples/inference_low_light.ipynb
  docs/examples/train_fast_zero_dce.ipynb
  docs/examples/train_mirnetv2.ipynb
  docs/examples/train_nafnet.ipynb
  docs/examples/train_zero_dce.ipynb
  docs/losses/zero_reference.md
  docs/metrics.md
  experiments/evaluate.py
  experiments/inference.ipynb
  experiments/low_light_enhancement/supervised/mirnetv2/low_light_config.py
  experiments/low_light_enhancement/supervised/mirnetv2/train_mirnetv2.ipynb
  experiments/low_light_enhancement/supervised/mirnetv2/train_mirnetv2.py
  experiments/low_light_enhancement/supervised/nafnet/low_light_config.py
  experiments/low_light_enhancement/supervised/nafnet/train_nafnet.ipynb
  experiments/low_light_enhancement/supervised/nafnet/train_nafnet.py
  experiments/low_light_enhancement/unsupervised/low_light_config.py
  experiments/low_light_enhancement/unsupervised/train.py
  experiments/low_light_enhancement/unsupervised/train_zero_dce.ipynb
  mkdocs.yml
  pyproject.toml
  restorers/evaluation/lol_eval.py
  restorers/inference/low_light.py
  restorers/losses/charbonnier_loss.py
  restorers/losses/psnr_loss.py
  restorers/losses/spatial_consistency_loss.py
  restorers/losses/zero_reference.py
  restorers/metrics.py
  restorers/model/mirnetv2/downsample.py
  restorers/model/mirnetv2/mirnet.py
  restorers/model/mirnetv2/mrb.py
  restorers/model/mirnetv2/rcb.py
  restorers/model/mirnetv2/recursive_residual_group.py
  restorers/model/mirnetv2/skff.py
  restorers/model/mirnetv2/upsample.py
  restorers/model/nafnet/nafblock.py
  restorers/model/nafnet/nafnet.py
  restorers/model/zero_dce/dce_layer.py
  restorers/model/zero_dce/dw_conv.py
  restorers/model/zero_dce/fast_zero_dce.py
  restorers/model/zero_dce/zero_dce.py
Labels: documentation, enhancement, workflow, deploy

#70 refactor: Inheritance Structure of UnsupervisedLOLDataLoader
  .github/workflows/docs.yml
  .github/workflows/pypi-publish.yml
  .pre-commit-config.yaml
  README.md
  docs/examples/train_zero_dce.ipynb
  docs/index.md
  pyproject.toml
  restorers/__init__.py
  restorers/dataloader/__init__.py
  restorers/dataloader/base/__init__.py
  restorers/dataloader/base/base_low_light_dataloader.py
  restorers/dataloader/large_low_light_dataloader.py
  restorers/dataloader/lol_dataloader.py
Labels: documentation, dataloader
